### ISSUE TITLE
变分推断那里是不是有一点小错误

### ISSUE THREAD

**Issue by thinkwee** [roboticcam/machine-learning-notes#4]
pdf第九页将ELOB改写成KL散度时应该是qi(Zi)和那个伪分布p(X,Z)之间的KL散度吧，所以之后的迭代公式里更新的是ln(qj(zj))而不是qj(zj)

**Comment by Ravi-Jay** [comment]
嗯，同样发现了这个问题，KL散度的公式里期望前面应该加个exp。

**Comment by Matrixsun** [comment]
> 嗯，同样发现了这个问题，KL散度的公式里期望前面应该加个exp。

第9页的KL 散度 的期望前面不需要添加exp吧,  因为这个公式直接根据上一行的L(qj) 紧扣KL 定义得到的

**Comment by Matrixsun** [comment]
> pdf第九页将ELOB改写成KL散度时应该是qi(Zi)和那个伪分布p(X,Z)之间的KL散度吧，所以之后的迭代公式里更新的是ln(qj(zj))而不是qj(zj)

“pdf第九页将ELOB改写成KL散度时应该是qi(Zi)和那个伪分布p(X,Z)之间的KL散度吧” 为什么是qi(zi),  我理解 qi(zi)在第9页第一个 公式中被积没了。
